name: exofilt
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy=1.26.0
  - scipy=1.11.3
  - pandas=2.1.1
  - matplotlib=3.8.0
  - scikit-image=0.22.0
  - h5py=3.9.0
  - pillow=9.4.0
  - jupyterlab=4.0.6
  - pip:
      - tensorflow==2.10.0
      - keras==2.10.0
      - keras-preprocessing==1.1.2
      - tensorflow-estimator==2.10.0
      - tensorboard==2.10.1
      - protobuf==3.19.6
      - absl-py==1.4.0
      - google-auth-oauthlib==0.4.6
